
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping_cart
    ports:
      - "3300:3306"
    networks:
      - backend

  gateway-service:
    build: ./gateway-api
    environment:
      - JWT_SECRET=Z3sOhmRhZG9yLXR1LWaVanJldGUtY29uLXNvbG9yaW8tcGFyYS1sYS1jbGF2ZS1kZWotanVnaW1lbnRvLWhzNTEyLXNlY3JldA==
    ports:
      - "8080:8080"
    networks:
      - backend

  auth-service:
    build: ./auth-api
    environment:
      - DB_URL=jdbc:mysql://db:3306/shopping_cart
      - DB_USER=root
      - DB_PASSWORD=root
      - JWT_SECRET=Z3sOhmRhZG9yLXR1LWaVanJldGUtY29uLXNvbG9yaW8tcGFyYS1sYS1jbGF2ZS1kZWotanVnaW1lbnRvLWhzNTEyLXNlY3JldA==
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - backend

  product-service:
    build: ./product-api
    environment:
      - DB_URL=jdbc:mysql://db:3306/shopping_cart
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db
    ports:
      - "8082:8082"
    networks:
      - backend

  customer-service:
    build: ./customer-api
    environment:
      - DB_URL=jdbc:mysql://db:3306/shopping_cart
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db
    ports:
      - "8083:8083"
    networks:
      - backend

  order-service:
    build: ./order-api
    environment:
      - DB_URL=jdbc:mysql://db:3306/shopping_cart
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db
    ports:
      - "8084:8084"
    networks:
      - backend

  detail-service:
    build: ./detail-api
    environment:
      - DB_URL=jdbc:mysql://db:3306/shopping_cart
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db
    ports:
      - "8085:8085"
    networks:
      - backend

  payment-service:
    build: ./payment-api
    environment:
      - DB_URL=jdbc:mysql://db:3306/shopping_cart
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db
    ports:
      - "8086:8086"
    networks:
      - backend

networks:
  backend:
    driver: bridge
