spring.application.name=order-api
server.port=8084

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
spring.jpa.properties.hibernate.format_sql=true
jakarta.persistence.validation.mode=none

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoints.web.exposure.exclude=env,beans
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator

# Custom info
info.app.name=order-api-qa
info.app.version=1.0.0
info.app.description=order api

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.info.version=0.2.4

# Feign client URLs
services.customer.url=http://customer-service:8082/api/v1/customers
