spring.application.name=detail-api
server.port=8085

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
spring.jpa.properties.hibernate.format_sql=true
jakarta.persistence.validation.mode=none

# Auditoria
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.javax.persistence.validation.mode=none
# Activar auditoria
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.open-in-view=false

# Custom info
info.app.name=detail-api-prod
info.app.version=1.0.0
info.app.description=detail api

# Swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Feign client URLs
services.product.url=http://product-service:8083/api/v1/products
services.order.url=http://order-service:8084/api/v1/orders
