spring.application.name=product-api
server.port=8083

# Custom info
info.app.name=product-api-prod
info.app.version=1.0.0
info.app.description=Products api

# Swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

#Externals api
external.api=https://fakestoreapi.com
