spring.application.name=product-api-dev
server.port=8083

# Custom info
info.app.name=product-api
info.app.version=1.0.0
info.app.description=Products api

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#Externals api
external.api=https://fakestoreapi.com
